import Foundation

// MARK: - Plex Media Server naming conventions
//
// Official Plex naming guide:
//   https://support.plex.tv/articles/naming-and-organizing-your-movie-media-files/
//
// Required folder format:
//   Movies/
//     Movie Title (Year)/
//       Movie Title (Year).mkv        ← video file placed here manually
//
// With IMDb ID (recommended — eliminates all ambiguity):
//   Movies/
//     Movie Title (Year) {imdb-ttXXXXXXX}/
//       Movie Title (Year) {imdb-ttXXXXXXX}.mkv
//
// This generator produces only the directory path strings.
// The caller (or a shell script) is responsible for mkdir and moving ripped files.

public struct PlexFolderGenerator {

    public enum NamingStyle {
        /// "Movie Title (Year)"  — basic, no IMDb tag
        case basic
        /// "Movie Title (Year) {imdb-ttXXXXXXX}"  — preferred for accuracy
        case withIMDbID
    }

    public let style: NamingStyle
    /// Optional root folder prepended to every path, e.g. "/Volumes/Media/Movies"
    public let rootPath: String?

    public init(style: NamingStyle = .withIMDbID, rootPath: String? = nil) {
        self.style = style
        self.rootPath = rootPath
    }

    // MARK: - Folder name

    /// The bare folder name for a confirmed movie, e.g.
    /// `"The Matrix (1999) {imdb-tt0133093}"`
    public func folderName(for movie: MovieInfo) -> String {
        let base = "\(sanitize(movie.title)) (\(movie.year))"
        switch style {
        case .basic:
            return base
        case .withIMDbID:
            return "\(base) {imdb-\(movie.imdbID)}"
        }
    }

    // MARK: - Full path

    /// The full path including optional root, e.g.
    /// `/Volumes/Media/Movies/The Matrix (1999) {imdb-tt0133093}`
    public func folderPath(for movie: MovieInfo) -> String {
        let name = folderName(for: movie)
        if let root = rootPath, !root.isEmpty {
            return (root as NSString).appendingPathComponent(name)
        }
        return name
    }

    // MARK: - Generate PlexFolder descriptors from confirmed scans

    /// Convert a list of `DVDScan` objects (only confirmed ones) to `PlexFolder` descriptors.
    public func generate(from scans: [DVDScan]) -> [PlexFolder] {
        scans.compactMap { scan in
            guard let movie = scan.confirmedMovie else { return nil }
            let name = folderName(for: movie)
            return PlexFolder(scan: scan, folderName: name, fileBaseName: name)
        }
    }

    // MARK: - Shell script export

    /// Produces a `mkdir -p` shell script that creates all folders.
    /// Paste into Terminal or execute programmatically.
    public func shellScript(from folders: [PlexFolder]) -> String {
        var lines = ["#!/bin/sh", "# Generated by DVDScanner — paste into Terminal"]
        if let root = rootPath, !root.isEmpty {
            lines.append("ROOT=\(shellEscape(root))")
        } else {
            lines.append("ROOT=\"$HOME/Movies\"")
        }
        lines.append("")

        for folder in folders {
            let escaped = shellEscape(folder.folderName)
            lines.append("mkdir -p \"$ROOT/\(escaped)\"")
            // Placeholder comment for the video file
            lines.append("# Place your rip here: \"$ROOT/\(escaped)/\(escaped).mkv\"")
            lines.append("")
        }
        return lines.joined(separator: "\n")
    }

    // MARK: - Helpers

    /// Strip characters that are illegal in macOS/Windows/Linux directory names.
    private func sanitize(_ title: String) -> String {
        // Characters forbidden on macOS/APFS: / and null byte
        // Characters forbidden on Windows: \ / : * ? " < > |
        // Characters forbidden on Linux: / and null byte
        // We remove the superset so output works everywhere.
        let forbidden: CharacterSet = CharacterSet(charactersIn: #"\/:*?"<>|"#)
            .union(CharacterSet(charactersIn: "\0"))
        var result = title
            .unicodeScalars
            .filter { !forbidden.contains($0) }
            .map(Character.init)
            .map(String.init)
            .joined()

        // Collapse consecutive spaces and trim
        result = result
            .components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
            .trimmingCharacters(in: .whitespaces)

        // macOS doesn't allow names ending in a period
        while result.hasSuffix(".") {
            result = String(result.dropLast())
        }

        return result.isEmpty ? "Unknown" : result
    }

    /// Wrap a path in single quotes, escaping any single quotes within.
    private func shellEscape(_ s: String) -> String {
        "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}
